#
# Alerte au redemarrage de HA core
#
- alias: "Alerte au redemarrage de Home Assistant"
  description: Envoie une notification sur Telegram Ã  chaque redemarrage de HA core
  id: 75093260-3086-11eb-8655-7fbd7c468bda
  condition: []
  trigger:
    - !include ../../triggers/start_ha.yaml
  action:
    - !include ../../actions/notify_sm_a530_sg.yaml